name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish .NET Core Project
      if: github.event_name == 'push'
      run: dotnet publish EvolutionSim/EvolutionSim.csproj --configuration Release -p:GHPages=true --output dist/Web --nologo
    - name: Configure GitHub Pages
      if: github.event_name == 'push'
      uses: actions/configure-pages@v5
    - name: Upload GitHub Pages artifact
      if: github.event_name == 'push'
      uses: actions/upload-pages-artifact@v4
      with:
        path: dist/Web/wwwroot

  deploy:
    if: github.event_name == 'push'
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Deploy GitHub Pages site
      id: deployment
      uses: actions/deploy-pages@v4
